'use client';
import { useMemo, useState } from 'react';
import { PageFrame } from '@/components/PageFrame';
import { GoldButton, NeuCard, SoftCard } from '@/components/Neu';
import { useProject } from '@/components/ProjectProvider';
import { parsePronoteText } from '@/lib/parser';
import { SubjectIcon, Download, Target, CalendarDays } from '@/components/icons';
import { weekDates, sameDay, shortDate } from '@/lib/date';
import type { Quadrant, Task } from '@/lib/types';

export default function PlanningPage(){
 const {state,addTask,updateTask,organizeWeek}=useProject(); const [view,setView]=useState<'week'|'month'|'priorities'>('week'); const [raw,setRaw]=useState(''); const week=weekDates();
 const subject=(id?:string|null)=>state.subjects.find(s=>s.id===id);
 async function importText(){for(const t of parsePronoteText(raw,state.subjects)) await addTask(t);setRaw('');}
 const planned=state.tasks.filter(t=>t.plannedStart&&t.status!=='done');
 const monthDays=useMemo(()=>{const d=new Date();const first=new Date(d.getFullYear(),d.getMonth(),1);const start=new Date(first);start.setDate(1-((first.getDay()+6)%7));return Array.from({length:42},(_,i)=>{const x=new Date(start);x.setDate(start.getDate()+i);return x})},[]);
 function moveToDay(task:Task,day:Date){const d=new Date(day);d.setHours(18,0,0,0);updateTask(task.id,{plannedStart:d.toISOString()});}
 function quadrantTitle(q:Quadrant){return q==='do'?'Urgent + important':q==='schedule'?'Important':q==='delegate'?'Urgent secondaire':'À éliminer'}
 return <PageFrame><div className="page-head"><div><h1>Planning</h1><p>Semaine du {week[0].getDate()} au {week[6].getDate()} {week[6].toLocaleDateString('fr-FR',{month:'long'})}</p></div><div className="segmented">{(['week','month','priorities'] as const).map(v=><button key={v} className={view===v?'selected':''} onClick={()=>setView(v)}>{v==='week'?'Semaine':v==='month'?'Mois':'Priorités'}</button>)}</div></div>
 <NeuCard className="pronote"><div className="small-glyph"><Download/></div><div><h2 style={{fontSize:24,marginBottom:8}}>Ajouter depuis Pronote</h2><textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder="Ex. : Maths ex 12-18 jeudi, contrôle de PC vendredi…"/></div><GoldButton onClick={importText}>Importer →</GoldButton></NeuCard>
 {view==='week'&&<div className="calendar-layout"><NeuCard className="week-grid"><div className="section-title"><h2>Mon planning</h2></div><div className="week-head"><div/>{week.map(d=><div key={d.toISOString()}>{d.toLocaleDateString('fr-FR',{weekday:'short'})}<br/>{d.getDate()}</div>)}</div><div className="week-body"><div className="hours">{Array.from({length:13},(_,i)=><span key={i}>{8+i}h</span>)}</div>{week.map(day=><div key={day.toISOString()} className="day-column" onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData('text/task');const t=state.tasks.find(x=>x.id===id);if(t)moveToDay(t,day)}}>{planned.filter(t=>sameDay(new Date(t.plannedStart!),day)).map(t=>{const h=new Date(t.plannedStart!).getHours();return <div draggable onDragStart={e=>e.dataTransfer.setData('text/task',t.id)} className="calendar-task" key={t.id} style={{top:(h-8)*44+4,height:Math.max(48,t.durationMin/60*44)}}><strong>{subject(t.subjectId)?.name||'Travail'}</strong>{t.title}</div>})}</div>)}</div></NeuCard><aside className="side-actions"><NeuCard className="list-card"><div className="section-title"><h2>À venir</h2></div>{state.tasks.filter(t=>t.dueAt&&t.status!=='done').sort((a,b)=>new Date(a.dueAt!).getTime()-new Date(b.dueAt!).getTime()).slice(0,5).map(t=><div className="task-row" key={t.id}><div className="small-glyph"><SubjectIcon icon={subject(t.subjectId)?.icon||'file'} size={22}/></div><div className="task-copy"><strong>{subject(t.subjectId)?.name||'Travail'}</strong><p>{t.title}</p></div><span className="task-time">{shortDate(t.dueAt)}</span></div>)}</NeuCard><SoftCard className="action-card" onClick={()=>setView('priorities')}><div className="small-glyph"><Target/></div><div><strong>Prioriser</strong><p>Classe les tâches importantes.</p></div></SoftCard><SoftCard className="action-card" onClick={organizeWeek}><div className="small-glyph"><CalendarDays/></div><div><strong>Organiser ma semaine</strong><p>Crée des créneaux automatiquement.</p></div></SoftCard></aside></div>}
 {view==='month'&&<NeuCard className="month-grid">{monthDays.map(d=>{const list=state.tasks.filter(t=>t.dueAt&&sameDay(new Date(t.dueAt),d));return <div className="month-cell" key={d.toISOString()}><strong>{d.getDate()}</strong>{list.slice(0,3).map(t=><span key={t.id}>{subject(t.subjectId)?.shortName||'Travail'} · {t.title.slice(0,24)}</span>)}</div>})}</NeuCard>}
 {view==='priorities'&&<NeuCard className="matrix">{(['do','schedule','delegate','eliminate'] as Quadrant[]).map(q=><SoftCard className="quadrant" key={q} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData('text/task');if(id)updateTask(id,{quadrant:q})}}><h3>{quadrantTitle(q)}</h3><p>Glisse les tâches ici.</p>{state.tasks.filter(t=>t.status!=='done'&&t.quadrant===q).map(t=><div className="matrix-task" draggable onDragStart={e=>e.dataTransfer.setData('text/task',t.id)} key={t.id}>{subject(t.subjectId)?.shortName} — {t.title}</div>)}</SoftCard>)}</NeuCard>}
 </PageFrame>
}
