'use client';
import Link from 'next/link';
import { PageFrame } from '@/components/PageFrame';
import { NeuCard } from '@/components/Neu';
import { useProject } from '@/components/ProjectProvider';
import { SubjectIcon } from '@/components/icons';
import { subjectAverage, generalAverage } from '@/lib/grades';
import { shortDate } from '@/lib/date';
export default function SubjectsPage(){const {state}=useProject();const upcoming=state.tasks.filter(t=>t.kind==='exam'&&t.status!=='done').length;return <PageFrame><div className="page-head"><div><h1>Matières</h1><p>Vue scolaire générale</p></div></div><div className="subject-grid">{state.subjects.map(s=>{const avg=subjectAverage(state.grades,s.id);const chapters=state.chapters.filter(c=>c.subjectId===s.id);const solid=chapters.filter(c=>['solid','mastered'].includes(c.status)).length;const progress=chapters.length?Math.round(solid/chapters.length*100):0;const next=state.tasks.filter(t=>t.subjectId===s.id&&t.dueAt&&t.status!=='done').sort((a,b)=>new Date(a.dueAt!).getTime()-new Date(b.dueAt!).getTime())[0];return <Link href={`/subjects/${s.id}`} key={s.id}><NeuCard className="subject-card"><div className="subject-card-head"><div className="subject-glyph"><SubjectIcon icon={s.icon} size={34}/></div><h2>{s.name}</h2></div><div className="average">{avg??'—'}<small>{avg?'/20':''}</small></div><div className="progress"><i style={{width:`${progress}%`}}/></div><div className="subject-card-meta"><div>{chapters.length} chapitres<br/><span>{solid} solides</span></div><div>Prochain contrôle<br/><span>{shortDate(next?.dueAt)}</span></div></div></NeuCard></Link>})}</div><NeuCard className="overview-strip"><div className="overview-stat"><span>MOYENNE GÉNÉRALE</span><strong>{generalAverage(state.grades)??'—'}/20</strong></div><div className="overview-stat"><span>CONTRÔLES À VENIR</span><strong>{upcoming}</strong></div><div className="overview-stat"><span>DEVOIRS EN COURS</span><strong>{state.tasks.filter(t=>t.kind==='homework'&&t.status!=='done').length}</strong></div><div className="overview-stat"><span>HEURES TRAVAILLÉES</span><strong>{Math.round(state.sessions.reduce((a,s)=>a+s.durationMin,0)/6)/10} h</strong></div></NeuCard></PageFrame>}
